---
apiVersion: v1
kind: Pod
metadata:
  name: adas-nginx
  labels:
    app: nginx
    rel: demo
spec:
  containers:
  - name: adas-nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
    livenessProbe:
      httpGet:
        path: /index.html
        port: 80
      initialDelaySeconds: 15
      timeoutSeconds: 1
      periodSeconds: 5
      failureThreshold: 1