apiVersion: v1
kind: Pod
metadata:
  name: static-web
  labels:
    role: myrole
    app: web
    rel: test
spec:
  containers:
    - name: web
      image: nginx:alpine
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
      livenessProbe:
        httpGet:
          path: /index.html
          port: 80
        initialDelaySeconds: 2
        periodSeconds: 5
        failureThreshold: 1